In [22]:
#importing library

In [23]:
import numpy as np
import pandas as pd

In [24]:
df=pd.read_csv('mail.csv')

In [25]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
y=df['Category']

In [26]:
#label encoding y value

In [5]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
y=l.fit_transform(y)
print(y)

[0 0 1 ... 0 0 0]


In [6]:
len(y)

5572

In [7]:
df['Message'].head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: Message, dtype: object

In [28]:
#importing nltk and re module
#text cleaning 
#applying tokenization
#stemming
#removing stop words

In [29]:
import re
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
from nltk.corpus import stopwords
words=stopwords.words('english')
print(words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [9]:
df["Message"][0]
corpus=[]

In [10]:
for i in range(0,5572):    
    m=[]
    m=re.sub('[^a-zA-Z]'," ",df["Message"][i])
    m=m.lower()
    m=m.split()
    filtered=[]
    for x in m:
         if x not in words:
            if len(x)>1:
                ps.stem(x)
                filtered.append(x)
    filtered=' '.join(filtered)
    corpus.append(filtered)

In [11]:
len(corpus)

5572

In [30]:
#bag of word model

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv=CountVectorizer()

In [14]:
x=cv.fit_transform(corpus).toarray()

In [15]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
#splitting data in training and testing

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20,)

In [35]:
#applying naive bayes classifier

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
g=MultinomialNB()

In [38]:
g.fit(x,y)

MultinomialNB()

In [39]:
y_pred = g.predict(x_test)

In [40]:
#predicting score

In [41]:
from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[958   2]
 [  2 153]]


0.9964125560538116